import type { Metadata } from 'next';
import './globals.css';
import NavBar from '@/components/Layout/NavBar';
import Footer from '@/components/Layout/Footer';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<NavBar />
				<main className="mt-[100px]">{children}</main>
				<Footer />
			</body>
		</html>
	);
}
